import Head from "next/head";
import type { AppProps } from "next/app";
import NextNProgress from "nextjs-progressbar";
import { CartContextProvider } from "@/context/CartContext";
import "@/styles/globals.css";

export default function App({ Component, pageProps }: AppProps) {
	return (
		<>
			<NextNProgress
				color="#F86600"
				height={4}
				options={{ showSpinner: false }}
			/>
			<Head>
				<title>
					Онлайн-сервис по мониторингу и уничтожению опасных астероидов
				</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<CartContextProvider>
				<Component {...pageProps} />
			</CartContextProvider>
		</>
	);
}
